### ISSUE TITLE
General question: multiple arrows

### ISSUE THREAD

**Issue by rhao** [american-art/autry#41]
What does it mean when you see multiple arrows entering a class? For example, in Object Primary Title, <primary_title_text> has two incoming arrows, but karma only supports one arrow to a column (although you can do multiple to a class instance).

**Comment by azaroth42** [comment]
The same information is used as the value of the appellation, and the label of the object.

```
_:x a crm:E22_ManMadeObject ;
  rdfs:label "title text" ;
  crm:P102_has_title [
    a crm:E35_Title ;
    rdf:value "title text" ] .
```

**Comment by rhao** [comment]
What about the case where there are two relations between the same two things? For example, if you look at Object Preferred ID (http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_24-search_0), the link between E42_Identifier and <identifier> is labeled as both rdfs:label and rdf:value. Do I use both?

I'm asking because I think the only way I can do this with karma is to duplicate the column, which is a bit weird, so I wanted to make sure that you intended to have both of these.

**Comment by workergnome** [comment]
I do:  There's nothing wrong or strange about two predicates between the same entities.  Think about a (theoretical) couple—they're husband/wife, but they're also friends, and they're also roommates.  All of these are different relationships, so they'd get different predicates—and you can't stack them, because they're not universally true.

In this case, we're talking about something that is both the label for an entity (the human-readable text that describes it) and also the actual value.  There's nothing in RDF that prevents this, so whatever work-around you need to use in Karma to make it possible is fine by me.
