### ISSUE TITLE
Something strange with objects & books...

### ISSUE THREAD

**Issue by workergnome** [american-art/autry#54]
If you look at this:

http://data.americanartcollaborative.org/page/autry/object/2012171

It appears to be two items, merged—there are two home pages, two titles, etc.

**Comment by AutryIT** [comment]
I'm not sure why this publication would behave differently than the others.  Could it be the + in the title?

**Comment by workergnome** [comment]
Are books in a different table then objects?  It looks like two different objects are being combined, which would happen if they both were given the same URI.

**Comment by AutryIT** [comment]
This is a publication related to the object, not exactly a book - more like a reference. It should be in a different table.  I was able to see the data last night I had thought it was referring to a publication.  I can't see the data right now to confirm.

**Comment by workergnome** [comment]
@bsnikhila, can you check on this?  I think two things are mapped to the same URI.

**Comment by bsnikhila** [comment]
There are 2 files : AutryObjects.xlsx and AutryPublications.xlsx
Both of them have fields "Title". So it seems like while building the model, records in the AutryPublications.xlsx have been considered as separate objects. But since the Object IDs are same, it's showing up as two(or more) titles for every object.
How would you like me to model this file? The review site does not seem to have anything explicitly for publications related to an object.

**Comment by AutryIT** [comment]
oh sorry.  I originally named that field "Title_Author" then I changed it to "Title" 
How can I change it back to "Title_Author"?

**Comment by AutryIT** [comment]
Our data will have the same problem with the CreditLine field which exists, but has different meaning, in both the AutryMedia and AutryObjects data files.

**Comment by AutryIT** [comment]
Ready to close, since publications weren't used
