### ISSUE TITLE
credit line URLs are...too long.

### ISSUE THREAD

**Issue by workergnome** [american-art/autry#55]
I don't think that this is really an appropriate URL:

http://data.americanartcollaborative.org/page/autry/object/credit_line/autrymuseumthepurchaseofthissculpturewasmadepossiblethroughthegenerosityofthefollowingindividualsedwardmcarsonpeggyandrobertdunnsaralynnandjohngeraghtymarilynbandcalvinbgrossmelodyandstuartjohnsonsettlerswestgallerieskcandrobertkaufmanwendieandstevenolshanrosellaandcarlthorneannalouandrobertlweirinmemoryofwilliamdweirandsandraalanandamywhitman

Perhaps you could use the object ID and something other than the full text?

**Comment by AutryIT** [comment]
oh - sorry, I didn't have this in mind as our URI format.  

Is it possible for the URI for the object to be:
http://data.americanartcollaborative.org/page/autry/object/200981

and the URI for the credit line related to that object be:
http://data.americanartcollaborative.org/page/autry/object/credit_line/200981

**Comment by VladimirAlexiev** [comment]
@bsnikhila 
- better http://data.americanartcollaborative.org/page/autry/object/200981/credit_line, i.e. construct it hierarchically: "credit_line" is a sub-node that belongs to ("is owned by") the main "object" node. This also relates to "URL hackability"
- please note the semantic URL is http://data.americanartcollaborative.org/autry/object/200981/credit_line (i.e. has neither "data" nor "page"). Everyone knows that, I'm mentioning it just in case.
- Maker URLs use names, eg http://data.americanartcollaborative.org/autry/maker/johnsmith. That's not too long, but the problem is that if there are two different John Smith, you will mix up their data. It's better to use the maker ID, which you can see in https://github.com/american-art/autry/issues/58
- Title URLs also use names, better to use `<object/nnnn/title>`

**Comment by kateblanch** [comment]
A good comparison is to look at the way medium text is mapped. The long text string is rdf:value, and not part of the URI. This definitely needs to be fixed.

**Comment by bsnikhila** [comment]
Changed it.
http://data.americanartcollaborative.org/page/autry/object/200981/credit_line
