### ISSUE TITLE
Autry Maker ULAN links

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#59]
@bsnikhila: Many AutryMakers have ULAN IDs. The [Actor LOD identifier mapping](http://review.americanartcollaborative.org/entity/E39_Actor#field_10-search_0) specifies you should emit them eg like this:
```ttl
@prefix ulan: <http://vocab.getty.edu/ulan/>.
<http://data.americanartcollaborative.org/autry/maker/abeytatony> skos:exactMatch ulan:500126291.
ulan:500126291 skos:inScheme ulan: .
```
(Related to https://github.com/american-art/aac_mappings/issues/56)

The mapping also says to attach a label to the ULAN node. However, you shouldn't get that label from the Autry data. @workergnome should get it from the GVP endpoint, eg
```sparql
select * {
  ulan:500126291 gvp:prefLabelGVP/xl:literalForm ?lab
}
```

@kateblanch @caknoblock I hope the Linking tool uses such explicit LOD ID's when they are present in the data?

**Comment by workergnome** [comment]
I agree with this—currently, we're running into the problem where the labels are coming from ULAN, but they're adding ALL the rdfs:labels, not the gvp:prefLabelGVP, so I have many, many labels to chose from and no way of knowing which one to choose.

**Comment by szeke** [comment]
@bsnikhila: the mapping process (Karma) should not do joins with ULAN. It should emit the ULAN URI if present in the source data, but should not query the ULAN endpoint to augment the data.

We can do dataset augmentation after the linking process. That is, after doing linking, the dataset can be augmented by joining with external endpoints. This is a separate process that can be done to cache data from external endpoints on our endpoint. I don't recommend doing this.

As @VladimirAlexiev suggests, @workergnome can dereference URIs to obtain additional information (this is the linked data way)

**Comment by workergnome** [comment]
Hi, all—

What we're trying to do here I find the most effective location to have a minimal cache.  I can certainly dereference the URIs, but I would either have to come up with some form of secondary cache, or query ULAN/AAT on every view/build of the site, and every time I re-query the data. 

The suggestion, which we've discussed before, and have encoded into our mappings, is for the triple store to have a label and a dataset associated with each external reference, so that the emitted data is usable without dereferencing for trivial uses, and to dereference when a more complicated use-case is needed, to avoid over-caching.

**Comment by bsnikhila** [comment]
I have added the ULAN links.
Ex : http://data.americanartcollaborative.org/page/autry/maker/readthomasbuchanan

**Comment by workergnome** [comment]
I see the scheme, but not the label:

http://yasgui.org/short/HkYIonXTg

**Comment by bsnikhila** [comment]
Added.
