### ISSUE TITLE
Browse app: one field not displaying

### ISSUE THREAD

**Issue by AutryIT** [american-art/autry#66]
I'm not sure if every field is supposed to display in the Browse App at this juncture, but all of our fields are displaying except for the Culture field.  Is it supposed to be there?

**Comment by workergnome** [comment]
That's almost certainly an oversight.  Can you give me an example of one where you'd expect it, and what you'd expect the value to be, and I'll figure out where it got lost?

**Comment by workergnome** [comment]
Also, should this apply to people, or to works?

**Comment by workergnome** [comment]
Had a long conversation with @azaroth42 about this today.

Our current conclusion is that there are two meanings to "culture".  

One is a culture associated with the actor:  David Newbury is "Welsh-American".  It's different than nationality, in that it is geo-political rather than cultural, but it's a similar sort of concept.

The other is the aesthetic culture associated with an object:  My dishes are "Japanese".  This doesn't mean they were produced in Japan, nor that the producer was culturally Japanese, but that they're celadon lotus-blossom plates.  

Our current feeling is that distinguishing between, say, "French", "Napoleonic", and "Impressionist" as styles is a very, very difficult problem, and is best handled at the level of vocabulary, not object modeling.  [CDWA's guidelines](http://www.getty.edu/research/publications/electronic_publications/cdwa/17styles.html#qualifier) agree that the complexity of qualifying styles is difficult and to be avoided.

Obviously, this is an essential part of your museum's practice, and we're more than willing to take input and suggestions about this, but our current suggestion is to model the 'Culture' field using the [Style](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_10-search_0) mapping.

**Comment by AutryIT** [comment]
Related to our records with Culture associated with an object, eg, http://data.americanartcollaborative.org/page/autry/object/89541: 
I agree that I don't like to use Styles for our Culture attribution.  I protested to the mapping when I first saw it, but I didn't come up with an alternate, so I think that's why it was left as is.  In our collections, we define the Culture attribution as made/used by.  In our AAC contribution, Culture indicates "made by."  It does not indicate style or time period.  

I'm not familiar enough with CIDOC CRM to be able to look for the correct mapping.

**Comment by AutryIT** [comment]
Related to our records with Nationality associated with a person, eg, http://data.americanartcollaborative.org/page/autry/maker/aguilarlinda:
This data is not consistent.  Some of it relates to cultural affiliation of the individual and some of it is a geo-political attribution.  I can field this data more specifically, but the group decided it wasn't worth it.  It is mapped as member, which is okay with us.  This one is mapped to the Browse app already.

**Comment by AutryIT** [comment]
For objects, we could use AAT's cultural groups:
http://vocab.getty.edu/aat/300387171

Does this make any sense?:
So it would be something like: 
produced by (P108i) -> carried out by (P14) = http://data.americanartcollaborative.org/page/autry/thesauri/culture/yankton = type: E74_Group and has_Type (P2) http://vocab.getty.edu/aat/300387171

**Comment by workergnome** [comment]
I think that treating culture and nationality as groups that Actors are members of makes a lot of sense, with http://vocab.getty.edu/aat/300387171 for culture. 


For objects, if the meaning is "the person who made this is a member of this culture", we can also just use that pattern.

**Comment by workergnome** [comment]
We could use the form you suggest:

```
_:object produced_by _:production.

_:production carried_out_by _:yankton.

_:yankton a crm:E74_Group;
   crm:p2_has_type aat:300387171.
```

But that would imply that the entire group had a direct hand in making the object.  Is that semantically what you want to imply?  The Scope Notes indicate that it is: 

> active participation of an E39 Actor...It implies causal or legal responsibility.

**Comment by AutryIT** [comment]
Yeah, that would certainly be an amazing collaborative project!  If we can use the crm to state: "the person who made this is a member of this culture" that would be best.  Otherwise, I think I do prefer implying the entire group made it, over reducing a whole culture to a time period/style.

**Comment by workergnome** [comment]
OK! @bsnikhila—

Let's map "culture" onto the Actor, using the same model as Nationality (http://review.americanartcollaborative.org/entity/E39_Actor#field_13-search_0), but instead of using http://vocab.getty.edu/aat/300379842 (nationality), as the type, use http://vocab.getty.edu/aat/300387171 (cultural groups)
