### ISSUE TITLE
Autry maker URLs should use ID not name

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#73]
What's wrong with a URL like http://data.americanartcollaborative.org/autry/maker/brownbob? You may  well have several John Smith.
You got the ID: http://data.americanartcollaborative.org/autry/maker/brownbob/pref_id so use it, eg the URLs should be:
http://data.americanartcollaborative.org/autry/maker/PE206593
http://data.americanartcollaborative.org/autry/maker/PE206593/pref_id

**Comment by AutryIT** [comment]
I didn't want to use that identifier because in the future, I don't intend to retain it; however, I have no current plans to get rid of it.  I can add it in, but that would add a column to my data, which I believe is not allowed at this stage.

**Comment by kateblanch** [comment]
@caknoblock, @bsnikhila -- if @AutryIT  were able to upload a new Maker data set that has preferred id, could that new data be modeled? It seems like an important fix.

**Comment by caknoblock** [comment]
@AutryIT can add a column, just make sure it is added as the last column of the dataset so that nothing else needs to change. On Sep 22, 2017, at 12:12 PM, Kate Blanch <notifications@github.com> wrote:@caknoblock, @bsnikhila -- if @AutryIT  were able to upload a new Maker data set that has preferred id, could that new data be modeled? It seems like an important fix.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/american-art/autry","title":"american-art/autry","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/american-art/autry"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kateblanch in #73: @caknoblock, @bsnikhila -- if @AutryIT  were able to upload a new Maker data set that has preferred id, could that new data be modeled? It seems like an important fix."}],"action":{"name":"View Issue","url":"https://github.com/american-art/autry/issues/73#issuecomment-331535957"}}}

**Comment by kateblanch** [comment]
@AutryIT...what do you think about the feasibility of adding an id to the maker data?

**Comment by bsnikhila** [comment]
Done.
Ex: http://data.americanartcollaborative.org/page/autry/maker/pe206593
